#include "TobiiBuffer/utils.h"

#include <sstream>

namespace
{
    struct TobiiResearchStatusInfo
    {
        const char* _cName;     /* Name of Constant */
        int			_uVal;      /* Constant's value as int */
        const char* _cErrorTxt; /* Explanative text for error */
    };

    TobiiResearchStatusInfo lookupTobiiResearchStatus(TobiiResearchStatus trs_)
    {
        switch (trs_)
        {
            // the below is code generated by the matlab script tools/TobiiResearchEnumLister.m
            case TOBII_RESEARCH_STATUS_OK:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_OK", static_cast<int>(TOBII_RESEARCH_STATUS_OK), "No error"};
            case TOBII_RESEARCH_STATUS_FATAL_ERROR:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FATAL_ERROR", static_cast<int>(TOBII_RESEARCH_STATUS_FATAL_ERROR), "Fatal error"};
            case TOBII_RESEARCH_STATUS_INITIALIZE_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_INITIALIZE_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_INITIALIZE_FAILED), "Failed to initialize the API"};
            case TOBII_RESEARCH_STATUS_TERMINATE_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_TERMINATE_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_TERMINATE_FAILED), "Failed to terminate the API"};
            case TOBII_RESEARCH_STATUS_LOCALBROWSER_CREATE_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_LOCALBROWSER_CREATE_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_LOCALBROWSER_CREATE_FAILED), "Failed to create browser for finding local devices"};
            case TOBII_RESEARCH_STATUS_LOCALBROWSER_POLL_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_LOCALBROWSER_POLL_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_LOCALBROWSER_POLL_FAILED), "Failed to poll local devices"};
            case TOBII_RESEARCH_STATUS_ZEROCONFBROWSER_CREATE_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_ZEROCONFBROWSER_CREATE_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_ZEROCONFBROWSER_CREATE_FAILED), "Failed to create zero configuration browser"};
            case TOBII_RESEARCH_STATUS_ZEROCONFBROWSER_POLL_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_ZEROCONFBROWSER_POLL_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_ZEROCONFBROWSER_POLL_FAILED), "Failed to poll devices from zero configuration browser"};
            case TOBII_RESEARCH_STATUS_FILEBROWSER_CREATE_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FILEBROWSER_CREATE_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_FILEBROWSER_CREATE_FAILED), "Failed to create browser that looks for devices in file"};
            case TOBII_RESEARCH_STATUS_FILEBROWSER_POLL_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FILEBROWSER_POLL_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_FILEBROWSER_POLL_FAILED), "Failed to poll devices from file browser"};
            case TOBII_RESEARCH_STATUS_INVALID_PARAMETER:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_INVALID_PARAMETER", static_cast<int>(TOBII_RESEARCH_STATUS_INVALID_PARAMETER), "An invalid parameter was given to the method"};
            case TOBII_RESEARCH_STATUS_INVALID_OPERATION:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_INVALID_OPERATION", static_cast<int>(TOBII_RESEARCH_STATUS_INVALID_OPERATION), "The operation was invalid"};
            case TOBII_RESEARCH_STATUS_UNINITIALIZED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_UNINITIALIZED", static_cast<int>(TOBII_RESEARCH_STATUS_UNINITIALIZED), "Internal core error code"};
            case TOBII_RESEARCH_STATUS_OUT_OF_BOUNDS:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_OUT_OF_BOUNDS", static_cast<int>(TOBII_RESEARCH_STATUS_OUT_OF_BOUNDS), "A parameter is out of bounds"};
            case TOBII_RESEARCH_STATUS_DISPLAY_AREA_NOT_VALID:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_DISPLAY_AREA_NOT_VALID", static_cast<int>(TOBII_RESEARCH_STATUS_DISPLAY_AREA_NOT_VALID), "The display area is not valid"};
            case TOBII_RESEARCH_STATUS_BUFFER_TOO_SMALL:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_BUFFER_TOO_SMALL", static_cast<int>(TOBII_RESEARCH_STATUS_BUFFER_TOO_SMALL), "The buffer is too small"};
            case TOBII_RESEARCH_STATUS_NOT_INITIALIZED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_NOT_INITIALIZED", static_cast<int>(TOBII_RESEARCH_STATUS_NOT_INITIALIZED), "tobii_research_initialize has not been called"};
            case TOBII_RESEARCH_STATUS_ALREADY_INITIALIZED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_ALREADY_INITIALIZED", static_cast<int>(TOBII_RESEARCH_STATUS_ALREADY_INITIALIZED), "tobii_research_initialize has already been called"};
            case TOBII_RESEARCH_STATUS_SAVED_LICENSE_FAILED_TO_APPLY:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SAVED_LICENSE_FAILED_TO_APPLY", static_cast<int>(TOBII_RESEARCH_STATUS_SAVED_LICENSE_FAILED_TO_APPLY), "The license saved on the device failed to apply when connecting"};
            case TOBII_RESEARCH_STATUS_SE_INTERNAL:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_INTERNAL", static_cast<int>(TOBII_RESEARCH_STATUS_SE_INTERNAL), "Internal stream engine error"};
            case TOBII_RESEARCH_STATUS_SE_INSUFFICIENT_LICENSE:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_INSUFFICIENT_LICENSE", static_cast<int>(TOBII_RESEARCH_STATUS_SE_INSUFFICIENT_LICENSE), "The operation requires a higher license type"};
            case TOBII_RESEARCH_STATUS_SE_NOT_SUPPORTED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_NOT_SUPPORTED", static_cast<int>(TOBII_RESEARCH_STATUS_SE_NOT_SUPPORTED), "The operations isn"};
            case TOBII_RESEARCH_STATUS_SE_NOT_AVAILABLE:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_NOT_AVAILABLE", static_cast<int>(TOBII_RESEARCH_STATUS_SE_NOT_AVAILABLE), "The device is unavailable"};
            case TOBII_RESEARCH_STATUS_SE_CONNECTION_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_CONNECTION_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_SE_CONNECTION_FAILED), "Connection to the device failed"};
            case TOBII_RESEARCH_STATUS_SE_TIMED_OUT:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_TIMED_OUT", static_cast<int>(TOBII_RESEARCH_STATUS_SE_TIMED_OUT), "The operation timed out"};
            case TOBII_RESEARCH_STATUS_SE_ALLOCATION_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_ALLOCATION_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_SE_ALLOCATION_FAILED), "Failed to allocate memory"};
            case TOBII_RESEARCH_STATUS_SE_ALREADY_INITIALIZED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_ALREADY_INITIALIZED", static_cast<int>(TOBII_RESEARCH_STATUS_SE_ALREADY_INITIALIZED), "The API is already initialized"};
            case TOBII_RESEARCH_STATUS_SE_NOT_INITIALIZED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_NOT_INITIALIZED", static_cast<int>(TOBII_RESEARCH_STATUS_SE_NOT_INITIALIZED), "The API isn"};
            case TOBII_RESEARCH_STATUS_SE_INVALID_PARAMETER:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_INVALID_PARAMETER", static_cast<int>(TOBII_RESEARCH_STATUS_SE_INVALID_PARAMETER), "An invalid parameter was given to the method"};
            case TOBII_RESEARCH_STATUS_SE_CALIBRATION_ALREADY_STARTED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_CALIBRATION_ALREADY_STARTED", static_cast<int>(TOBII_RESEARCH_STATUS_SE_CALIBRATION_ALREADY_STARTED), "Calibration has already started"};
            case TOBII_RESEARCH_STATUS_SE_CALIBRATION_NOT_STARTED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_CALIBRATION_NOT_STARTED", static_cast<int>(TOBII_RESEARCH_STATUS_SE_CALIBRATION_NOT_STARTED), "Calibration isn"};
            case TOBII_RESEARCH_STATUS_SE_ALREADY_SUBSCRIBED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_ALREADY_SUBSCRIBED", static_cast<int>(TOBII_RESEARCH_STATUS_SE_ALREADY_SUBSCRIBED), "Already subscribed"};
            case TOBII_RESEARCH_STATUS_SE_NOT_SUBSCRIBED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_NOT_SUBSCRIBED", static_cast<int>(TOBII_RESEARCH_STATUS_SE_NOT_SUBSCRIBED), "Not subscribed"};
            case TOBII_RESEARCH_STATUS_SE_OPERATION_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_OPERATION_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_SE_OPERATION_FAILED), "Operation failed"};
            case TOBII_RESEARCH_STATUS_SE_CONFLICTING_API_INSTANCES:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_CONFLICTING_API_INSTANCES", static_cast<int>(TOBII_RESEARCH_STATUS_SE_CONFLICTING_API_INSTANCES), "Conflicting api instances"};
            case TOBII_RESEARCH_STATUS_SE_CALIBRATION_BUSY:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_CALIBRATION_BUSY", static_cast<int>(TOBII_RESEARCH_STATUS_SE_CALIBRATION_BUSY), "Calibration busy"};
            case TOBII_RESEARCH_STATUS_SE_CALLBACK_IN_PROGRESS:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_CALLBACK_IN_PROGRESS", static_cast<int>(TOBII_RESEARCH_STATUS_SE_CALLBACK_IN_PROGRESS), "Callback in progress"};
            case TOBII_RESEARCH_STATUS_SE_TOO_MANY_SUBSCRIBERS:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_TOO_MANY_SUBSCRIBERS", static_cast<int>(TOBII_RESEARCH_STATUS_SE_TOO_MANY_SUBSCRIBERS), "Too many users subscribed to a stream"};
            case TOBII_RESEARCH_STATUS_SE_BUFFER_TOO_SMALL:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_BUFFER_TOO_SMALL", static_cast<int>(TOBII_RESEARCH_STATUS_SE_BUFFER_TOO_SMALL), "The buffer is too small"};
            case TOBII_RESEARCH_STATUS_SE_FIRMWARE_NO_RESPONSE:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_SE_FIRMWARE_NO_RESPONSE", static_cast<int>(TOBII_RESEARCH_STATUS_SE_FIRMWARE_NO_RESPONSE), "No response from firmware"};
            case TOBII_RESEARCH_STATUS_FWUPGRADE_INTERNAL:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FWUPGRADE_INTERNAL", static_cast<int>(TOBII_RESEARCH_STATUS_FWUPGRADE_INTERNAL), "Internal error"};
            case TOBII_RESEARCH_STATUS_FWUPGRADE_NOT_SUPPORTED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FWUPGRADE_NOT_SUPPORTED", static_cast<int>(TOBII_RESEARCH_STATUS_FWUPGRADE_NOT_SUPPORTED), "Firmware upgrade is not supported"};
            case TOBII_RESEARCH_STATUS_FWUPGRADE_UNKNOWN_FIRMWARE_VERSION:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FWUPGRADE_UNKNOWN_FIRMWARE_VERSION", static_cast<int>(TOBII_RESEARCH_STATUS_FWUPGRADE_UNKNOWN_FIRMWARE_VERSION), "Unknown firmware version"};
            case TOBII_RESEARCH_STATUS_FWUPGRADE_CONNECTION_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FWUPGRADE_CONNECTION_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_FWUPGRADE_CONNECTION_FAILED), "Connection failed"};
            case TOBII_RESEARCH_STATUS_FWUPGRADE_INVALID_PARAMETER:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FWUPGRADE_INVALID_PARAMETER", static_cast<int>(TOBII_RESEARCH_STATUS_FWUPGRADE_INVALID_PARAMETER), "Invalid parameter"};
            case TOBII_RESEARCH_STATUS_FWUPGRADE_PACKAGE_DEVICE_MISMATCH:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FWUPGRADE_PACKAGE_DEVICE_MISMATCH", static_cast<int>(TOBII_RESEARCH_STATUS_FWUPGRADE_PACKAGE_DEVICE_MISMATCH), "Device mismatch"};
            case TOBII_RESEARCH_STATUS_FWUPGRADE_PARSE_RESPONSE:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FWUPGRADE_PARSE_RESPONSE", static_cast<int>(TOBII_RESEARCH_STATUS_FWUPGRADE_PARSE_RESPONSE), "Parse response"};
            case TOBII_RESEARCH_STATUS_FWUPGRADE_OPERATION_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FWUPGRADE_OPERATION_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_FWUPGRADE_OPERATION_FAILED), "The firmware upgrade operation failed"};
            case TOBII_RESEARCH_STATUS_FWUPGRADE_ALLOCATION_FAILED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FWUPGRADE_ALLOCATION_FAILED", static_cast<int>(TOBII_RESEARCH_STATUS_FWUPGRADE_ALLOCATION_FAILED), "Memory allocation failed during firmware upgrade"};
            case TOBII_RESEARCH_STATUS_FWUPGRADE_FIRMWARE_NO_RESPONSE:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FWUPGRADE_FIRMWARE_NO_RESPONSE", static_cast<int>(TOBII_RESEARCH_STATUS_FWUPGRADE_FIRMWARE_NO_RESPONSE), "The firmware failed to respond during firmware upgrade"};
            case TOBII_RESEARCH_STATUS_FWUPGRADE_DOWNGRADE_NOT_SUPPORTED:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_FWUPGRADE_DOWNGRADE_NOT_SUPPORTED", static_cast<int>(TOBII_RESEARCH_STATUS_FWUPGRADE_DOWNGRADE_NOT_SUPPORTED), "The firmware downgrade operation is not supported"};
            case TOBII_RESEARCH_STATUS_UNKNOWN:
                return TobiiResearchStatusInfo{"TOBII_RESEARCH_STATUS_UNKNOWN", static_cast<int>(TOBII_RESEARCH_STATUS_UNKNOWN), "Unknown error"};
            default:
            {
                std::stringstream os;
                os << "lookupTobiiResearchStatus: code " << trs_ << " unknown";
                DoExitWithMsg(os.str());
                return TobiiResearchStatusInfo{"", static_cast<int>(-999), ""};  // to shut up compiler warnings
            }
        }
    }

    struct TobiiResearchLogSourceInfo
    {
        const char* _cName;     /* Name of Constant */
        int			_uVal;      /* Constant's value as int */
        const char* _cErrorTxt; /* Explanative text for error */
    };

    TobiiResearchLogSourceInfo lookupTobiiResearchLogSource(TobiiResearchLogSource trl_)
    {
        switch (trl_)
        {
            // the below is code generated by the matlab script tools/TobiiResearchEnumLister.m
            case TOBII_RESEARCH_LOG_SOURCE_STREAM_ENGINE:
                return TobiiResearchLogSourceInfo{"TOBII_RESEARCH_LOG_SOURCE_STREAM_ENGINE", static_cast<int>(TOBII_RESEARCH_LOG_SOURCE_STREAM_ENGINE), "The log message is from stream engine"};
            case TOBII_RESEARCH_LOG_SOURCE_SDK:
                return TobiiResearchLogSourceInfo{"TOBII_RESEARCH_LOG_SOURCE_SDK", static_cast<int>(TOBII_RESEARCH_LOG_SOURCE_SDK), "The log message is from the SDK"};
            case TOBII_RESEARCH_LOG_SOURCE_FIRMWARE_UPGRADE:
                return TobiiResearchLogSourceInfo{"TOBII_RESEARCH_LOG_SOURCE_FIRMWARE_UPGRADE", static_cast<int>(TOBII_RESEARCH_LOG_SOURCE_FIRMWARE_UPGRADE), "The log message is from the firmware upgrade module"};
            default:
            {
                std::stringstream os;
                os << "lookupTobiiResearchLogSource: code " << trl_ << " unknown";
                DoExitWithMsg(os.str());
                return TobiiResearchLogSourceInfo{"", static_cast<int>(-999), ""};  // to shut up compiler warnings
            }
        }
    }

    struct TobiiResearchLogLevelInfo
    {
        const char* _cName;     /* Name of Constant */
        int			_uVal;      /* Constant's value as int */
        const char* _cErrorTxt; /* Explanative text for error */
    };

    TobiiResearchLogLevelInfo lookupTobiiResearchLogLevel(TobiiResearchLogLevel trl_)
    {
        switch (trl_)
        {
            // the below is code generated by the matlab script tools/TobiiResearchEnumLister.m
            case TOBII_RESEARCH_LOG_LEVEL_ERROR:
                return TobiiResearchLogLevelInfo{"TOBII_RESEARCH_LOG_LEVEL_ERROR", static_cast<int>(TOBII_RESEARCH_LOG_LEVEL_ERROR), "Error message"};
            case TOBII_RESEARCH_LOG_LEVEL_WARNING:
                return TobiiResearchLogLevelInfo{"TOBII_RESEARCH_LOG_LEVEL_WARNING", static_cast<int>(TOBII_RESEARCH_LOG_LEVEL_WARNING), "Warning message"};
            case TOBII_RESEARCH_LOG_LEVEL_INFORMATION:
                return TobiiResearchLogLevelInfo{"TOBII_RESEARCH_LOG_LEVEL_INFORMATION", static_cast<int>(TOBII_RESEARCH_LOG_LEVEL_INFORMATION), "Information message"};
            case TOBII_RESEARCH_LOG_LEVEL_DEBUG:
                return TobiiResearchLogLevelInfo{"TOBII_RESEARCH_LOG_LEVEL_DEBUG", static_cast<int>(TOBII_RESEARCH_LOG_LEVEL_DEBUG), "Debug message"};
            case TOBII_RESEARCH_LOG_LEVEL_TRACE:
                return TobiiResearchLogLevelInfo{"TOBII_RESEARCH_LOG_LEVEL_TRACE", static_cast<int>(TOBII_RESEARCH_LOG_LEVEL_TRACE), "Trace message"};
            default:
            {
                std::stringstream os;
                os << "lookupTobiiResearchLogLevel: code " << trl_ << " unknown";
                DoExitWithMsg(os.str());
                return TobiiResearchLogLevelInfo{"", static_cast<int>(-999), ""};  // to shut up compiler warnings
            }
        }
    }
}

std::string TobiiResearchStatusToString(TobiiResearchStatus trs_)
{
    return lookupTobiiResearchStatus(trs_)._cName;
}

std::string TobiiResearchStatusToExplanation(TobiiResearchStatus trs_)
{
    return lookupTobiiResearchStatus(trs_)._cErrorTxt;
}

std::string TobiiResearchLogSourceToString(TobiiResearchLogSource trl_)
{
    return lookupTobiiResearchLogSource(trl_)._cName;
}

std::string TobiiResearchLogSourceToExplanation(TobiiResearchLogSource trl_)
{
    return lookupTobiiResearchLogSource(trl_)._cErrorTxt;
}

std::string TobiiResearchLogLevelToString(TobiiResearchLogLevel trl_)
{
    return lookupTobiiResearchLogLevel(trl_)._cName;
}

std::string TobiiResearchLogLevelToExplanation(TobiiResearchLogLevel trl_)
{
    return lookupTobiiResearchLogLevel(trl_)._cErrorTxt;
}