%% GazeData
%
% Provides data for the Gaze.
%
%   gaze_data = GazeData(device_time_stamp,...
%                system_time_stamp,...
%                left_gaze_point_on_display_area,...
%                left_gaze_point_in_user_coordinate_system,...
%                left_gaze_point_validity,...
%                left_pupil_diameter,...
%                left_pupil_validity,...
%                left_gaze_origin_in_user_coordinate_system,...
%                left_gaze_origin_in_trackbox_coordinate_system,...
%                left_gaze_origin_validity,...
%                right_gaze_point_on_display_area,...
%                right_gaze_point_in_user_coordinate_system,...
%                right_gaze_point_validity,...
%                right_pupil_diameter,...
%                right_pupil_validity,...
%                right_gaze_origin_in_user_coordinate_system,...
%                right_gaze_origin_in_trackbox_coordinate_system,...
%                right_gaze_origin_validity)
%
%%
classdef GazeData 
    properties (SetAccess = immutable)
        %% LeftEye
        % Gets the gaze data (<../Gaze/EyeData.html EyeData>) for the left eye.
        %
        %   gaze_data.LeftEye
        %
        LeftEye
        %% RightEye
        % Gets the gaze data (<../Gaze/EyeData.html EyeData>) for the right eye.
        %
        %   gaze_data.RightEye
        %
        RightEye
        %% DeviceTimeStamp
        % Gets the time stamp according to the eye trackers internal clock.
        %
        %   gaze_data.DeviceTimeStamp
        %
        DeviceTimeStamp
        %% SystemTimeStamp
        % Gets the time stamp according to the computers internal clock.
        %
        %   gaze_data.SystemTimeStamp
        %
        SystemTimeStamp
    end
    
    methods
        function gaze_data = GazeData(device_time_stamp,...
            system_time_stamp,...
                left_gaze_point_on_display_area,...
                left_gaze_point_in_user_coordinate_system,...
                left_gaze_point_validity,...
                left_pupil_diameter,...
                left_pupil_validity,...
                left_gaze_origin_in_user_coordinate_system,...
                left_gaze_origin_in_trackbox_coordinate_system,...
                left_gaze_origin_validity,...
                right_gaze_point_on_display_area,...
                right_gaze_point_in_user_coordinate_system,...
                right_gaze_point_validity,...
                right_pupil_diameter,...
                right_pupil_validity,...
                right_gaze_origin_in_user_coordinate_system,...
                right_gaze_origin_in_trackbox_coordinate_system,...
                right_gaze_origin_validity)
            
            gaze_data.DeviceTimeStamp = device_time_stamp;
            
            gaze_data.SystemTimeStamp = system_time_stamp;
            
            gaze_data.LeftEye = EyeData(left_gaze_point_on_display_area,...
                left_gaze_point_in_user_coordinate_system,...
                left_gaze_point_validity,...
                left_pupil_diameter,...
                left_pupil_validity,...
                left_gaze_origin_in_user_coordinate_system,...
                left_gaze_origin_in_trackbox_coordinate_system,...
                left_gaze_origin_validity);
            
            gaze_data.RightEye = EyeData(right_gaze_point_on_display_area,...
                right_gaze_point_in_user_coordinate_system,...
                right_gaze_point_validity,...
                right_pupil_diameter,...
                right_pupil_validity,...
                right_gaze_origin_in_user_coordinate_system,...
                right_gaze_origin_in_trackbox_coordinate_system,...
                right_gaze_origin_validity);
            
        end
    end
    
end

%% See Also
% <../Gaze/EyeData.html EyeData>

%% Version
% !version
%
% Copyright !year Tobii Pro
%