function swaptime = drawtext(text, textSetup, w, flipWhen, qCenterEachLine)
extra = {};
if nargin>4 && ~isempty(qCenterEachLine) && qCenterEachLine
    extra = [extra {'xlayout', 'center'}];
end
DrawFormattedText2(text, 'win', w, ...
    'sx', 'center', 'xalign', 'center', 'sy', 'center', 'yalign', 'center', ...
    'baseColor', textSetup.color, ...
    'wrapat', textSetup.wrapAt, ...
    'vSpacing', textSetup.vSpacing,...
    extra{:});
swaptime = Screen('Flip',w,flipWhen);